### PR TITLE
Add an option for using custom dialog icons on MacOS

### PR DESCRIPTION
**Pull request by serge-belov**
I want to suggest an extension to the message dialog to allow custom icons, for example:

`zenity.Warning(
		"Text",
		zenity.Title("Title"),
		zenity.CustomIcon("some_icon.icns"))
`

The PR outlines the minimal implementation which would address our current needs, and I'm keen to understand your perspective: is that something you'd be willing to accept? If so, what else do I need to cover? 

I'd appreciate any feedback, and thanks for your work on the library.

### CODE REVIEW

**Comment by ncruces** [comment]
Sorry for not answering sooner, I haven't had much time.

This change raises the issue of what to do on other platforms.
I don't think `zenity` allows one to replace that icon with a custom one.
I'd have to look into what's easily supported on Windows.

Then there's also the issue of file formats. macOS requires `icns` I assume. `zenity` if it supports this, probably wants `png`. Windows I have no idea.

I need to fix the final instances of #20, that's my priority. And I haven't had time.
But I'll look into this.
Thanks!

**Comment by serge-belov** [comment]
Hey, no worries, and thanks, let me know if you need anything.

**Comment by ncruces** [comment]
Working on this on the [`ncruces:custom-icons`](https://github.com/ncruces/zenity/compare/custom-icons) branch.

macOS version is done, I think, can you test?
Needed to improve error handling and some corner cases.
I need to do Windows and Linux now.

Thanks!

**Comment by ncruces** [comment]
@serge-belov [v0.8.6](https://github.com/ncruces/zenity/releases/tag/v0.8.6) addresses this.

**Pull request merged**
